### PR TITLE
Modify foldmethod to use a comment expression

### PR DESCRIPTION
**Pull request by skoster**
Use "header" and "footer" comments to delineate section groupings. The
format is:

```
; +<Section>
...
; -<Section>
```
where `+<Section>` is the start of a section and `-<Section>` is the end of
the section.

The resulting format of the folds would be:
```
+-- 10 lines: +Assets/Income-------------------------------------

+-- 44 lines: +Expenses------------------------------------------
```

### CODE REVIEW

**Comment by xentac** [comment]
Do you not like using markdown sections as folds?  https://github.com/nathangrigg/vim-beancount/pull/12 made it possible to use # and * headers as folds.

**Comment by skoster** [comment]
Using ```#``` and ```*``` are fine and I think that most people would be satisfied with that method, however by having a delimiter for the end of each section makes it easy to jump to the last transaction of the section and start entering new transactions by typing ```]zO```. I also prefer the display of having a blank line between each section when they are all collapsed. Finally, I assume that it would be easier for someone to tweak the folding method to their own liking by allowing them to override the ```GetBeanCountFoldMethod```.

I'm far from a vim expert so there may be other ways to accomplish what I've done here. I just found that my method worked nicely for my needs and thought I'd share.

**Comment by nathangrigg** [comment]
The default mode of vim-beancount is to use vim markers, which work similar to what you implemented.


create a fold like this: 
```
; Section {{{


; }}} 
```

**Comment by skoster** [comment]
Ah, I missed that. Thanks for the heads-up. However, I did have to explicitly set the foldmethod to marker so either I'm missing something (very likely) or the default is not technically to use vim markers as you mentioned.

Regardless, that does everything that this pull request does, but in a cleaner fashion. Thank you.

**Comment by nathangrigg** [comment]
@skoster is right, the default fold method is 'syntax'. You can override the default using `set foldmethod=marker` in .vim/after/ftplugin/beancount.vim. Or you can override per-file with a comment like  `; vim: foldmethod=maker` in the first few lines or last line of your file.

**Pull request closed without merging**
